Repository AY2223S1-CS2103T-W12-4/tp, pull requests merged in 2022-11, with the labels that each got.

#206 user guide edits along with minor PPP changes
  docs/UserGuide.md
  docs/images/UpdatedUI.jpg
  docs/team/whysochong.md
Labels: documentation

#207 PPP and UG
  docs/UserGuide.md
  docs/images/AttendanceAdd.png
  docs/images/AttendanceDelete.png
  docs/images/AttendanceMark.png
  docs/team/evande1.md
Labels: documentation

#208 Update PPP
  docs/team/gowribhat.md
Labels: documentation

#213 Update PPP
  docs/team/thamruicong.md
Labels: documentation

#212 UG fixes
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui_annotated.png
  docs/index.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#215 Branch refactor task
  src/main/java/seedu/address/model/task/Assignment.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/TaskTitle.java
  src/main/java/seedu/address/model/task/ToDo.java
  src/test/java/seedu/address/model/task/TaskListTest.java
Labels: enhancement

#225 Fix bug in edit-task
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug

#227 Update DG with edit task
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/diagrams/AttendanceDeleteActivityDiagram.puml
  docs/diagrams/EditTaskActivityDiagram.puml
  docs/diagrams/EditTaskSequenceDiagram.puml
  docs/images/AddTaskActivityDiagram.png
  docs/images/AttendanceDeleteActivityDiagram.png
  docs/images/AttendanceDeleteSequenceDiagram.png
  docs/images/EditTaskActivityDiagram.png
  docs/images/EditTaskSequenceDiagram.png
  docs/team/gowribhat.md
Labels: documentation

#228 UG Fixes
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/minima/skins/classic.scss
Labels: documentation
