Repository AY2223S1-CS2103T-W12-4/tp, pull requests merged in 2022-10, with the labels that each got.

#46 Edit user stories
  docs/DeveloperGuide.md
Labels: documentation

#53 Update PPP
  docs/team/evande1.md
Labels: documentation

#55 added my own features in my PPP (v1.2)
  docs/team/whysochong.md
Labels: enhancement

#58 Create StudentId field for Students
  docs/UserGuide.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/StudentIdTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#59 Create Class field for Students
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClassGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClassGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/ClassGroup.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClassGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClassGroupCommandParserTest.java
  src/test/java/seedu/address/model/student/ClassGroupTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: enhancement, priority.High

#71 Merged branch
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: enhancement

#62 Improve searching using the Find command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/student/ClassGroup.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/ClassGroupTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/NameTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
  src/test/java/seedu/address/model/student/StudentContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/StudentIdTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: enhancement, priority.Mid

#79 Branch picture
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/UploadPictureCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UploadPictureCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Picture.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/ImageStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/resources/profile/default-profile-pic.jpg
Labels: enhancement

#81 Add attendance list without tests
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/evande1.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AttendanceAddCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceDeleteCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceMarkCommand.java
  src/main/java/seedu/address/logic/commands/ClassGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceAddCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendanceDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendanceMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/attendance/Attendance.java
  src/main/java/seedu/address/model/attendance/AttendanceList.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendanceList.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/AttendanceAddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceCommandParserTest.java
  src/test/java/seedu/address/model/attendance/AttendanceListTest.java
  src/test/java/seedu/address/model/attendance/AttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: enhancement

#83 More task test cases
  .gitignore
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement

#87 Update developer Guide with attendance for v1.3
  docs/DeveloperGuide.md
Labels: documentation

#86 Create diagrams for attendance
  docs/diagrams/AttendanceDeleteActivityDiagram.puml
  docs/diagrams/AttendanceDeleteSequenceDiagram.puml
  docs/images/AttendanceDeleteActivityDiagram.png
  docs/images/AttendanceDeleteSequenceDiagram.png
Labels: documentation

#92 Update Developer Guide with Class Group implementation for v1.3
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ClassGroupSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ClassGroupSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#95 Update DG for Upload Picture feature
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UploadPictureActivityDiagram.puml
  docs/diagrams/UploadPictureSequenceDiagram.puml
  docs/images/PictureUploadActivityDiagram.png
  docs/images/PictureUploadSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/UploadPictureCommand.java
  src/main/java/seedu/address/logic/parser/UploadPictureCommandParser.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/storage/ImageStorage.java
  src/test/java/seedu/address/logic/commands/UploadPictureCommandTest.java
  src/test/java/seedu/address/logic/parser/UploadPictureCommandParserTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: documentation, enhancement

#93 Fix minor issues
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#96 v1.3 Updated DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
Labels: documentation, enhancement

#97 Update dg for task feature
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddTaskActivityDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#99 v1.3 Deadline Implementation on TaskList
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/FormatDate.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/ToDo.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonAdaptedToDo.java
  src/main/java/seedu/address/storage/JsonSerializableTaskBook.java
  src/main/java/seedu/address/ui/DeadlineCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/java/seedu/address/ui/ToDoCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskBookTest/invalidTaskBook.json
  src/test/data/JsonSerializableTaskBookTest/typicalTaskBook.json
  src/test/data/JsonSerializableTaskBookTest/typicalTaskBookWithDeadlines.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClassGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/TaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UploadPictureCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TaskCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskBookTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedToDoTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskBookTest.java
  src/test/java/seedu/address/storage/JsonTaskBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/DeadlineBuilder.java
  src/test/java/seedu/address/testutil/ToDoBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeadlines.java
  src/test/java/seedu/address/testutil/TypicalToDos.java
Labels: enhancement

#103 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#107 Update UG with coming soon and FAQ
  docs/UserGuide.md
Labels: documentation

#108 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#111 Fix landing page
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#113 Add tests for InputHistory.java
  src/test/java/seedu/address/storage/InputHistoryTest.java
Labels: enhancement

#116 Fix error in code
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
Labels: bug

#114 Add User stories to DG
  docs/DeveloperGuide.md
Labels: documentation

#120 Branch dg use case
  docs/DeveloperGuide.md
Labels: documentation

#189 Add edit tasks to UG and format command summary table
  docs/UserGuide.md
Labels: documentation

#190 Fix typo in class command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClassGroupCommand.java
Labels: bug, documentation

#191 Attendance Logic test cases
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AttendanceMarkCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AttendanceAddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendanceMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AttendanceMarkCommandParserTest.java
  src/test/java/seedu/address/model/attendance/AttendanceListTest.java
  src/test/java/seedu/address/model/attendance/AttendanceTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: bug

#195 Branch pe d fixes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskTitle.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableTaskBookTest/invalidTaskBook.json
  src/test/data/JsonTaskBookStorageTest/invalidTaskBook.json
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/task/TaskTitleTest.java
Labels: bug

#196 Attendance error message fixes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendanceMarkCommandParser.java
Labels: bug

#201 Code reuse
  src/main/java/seedu/address/storage/InputHistory.java
  src/test/java/seedu/address/storage/InputHistoryTest.java
Labels: documentation

#202 Bug find
  src/main/java/seedu/address/logic/parser/ClassGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/ClassGroup.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Phone.java
  src/test/java/seedu/address/logic/parser/ClassGroupCommandParserTest.java
  src/test/java/seedu/address/model/student/ClassGroupTest.java
Labels: bug

#204 Make empty prefix clear the field data
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug
